# Generated by Django 2.2.4 on 2019-08-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190809_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Computer & Accessories', 'Computer & Accessories'), ('Mobile & Accessories', 'Mobile & Accessories'), ('Clothings', 'Clothings'), ('Electronics', 'Electronics'), ('Health & Beauty', 'Computer & Accessories'), ('Home & Lifestyle', 'Mobile & Accessories'), ('Sport', 'Sport'), ("Men's Fashion", "Men's Fashion"), ("Women's Fashion", "Women's Fashion"), ('Others', 'Others')], default='Others', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
