# Generated by Django 2.2.4 on 2019-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summary',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
