# Generated by Django 2.2.4 on 2019-08-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='summary',
        ),
    ]
