# Generated by Django 2.2.4 on 2019-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190814_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.ManyToManyField(null=True, to='product.Quant'),
        ),
    ]
