# Generated by Django 2.2.4 on 2019-08-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190814_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantities',
        ),
        migrations.DeleteModel(
            name='Quant',
        ),
    ]
